# More GitHub Actions for Azure: https://github.com/Azure/actions

name: zip and commit extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-and-commit:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: './repo/'

    - name: Remove old zip file
      uses: EndBug/add-and-commit@v9
      with:
        remove: 'extension.zip'
        cwd: './repo/'
        default_author: github_actions

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Create new zip file
      run: zip -qq -r ../extension.zip *
      working-directory: './repo/extension/'

    - name: Commit new zip file
      uses: EndBug/add-and-commit@v9
      with:
        add: 'extension.zip --force'
        cwd: './repo/'
        default_author: github_actions